# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
    - develop
  paths:
    include:
    - pipelines/ARM-deploy.yml

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  name: ARMTemplateDeployment
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Bijibiji Azure'
    subscriptionId: '<subscriptionID>'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-6309'
    location: 'eastus'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/boga5/Practice/main/ARM_templates/az_app_service/linux_app1/node_app1-deploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/boga5/Practice/main/ARM_templates/az_app_service/linux_app1/node_app1-parameters.json'
    deploymentMode: 'Incremental'
